// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoKeyValue.proto

package treeSem.proto;

public final class ProtoKeyValue {
  private ProtoKeyValue() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface KeyValueOrBuilder
          extends com.google.protobuf.MessageOrBuilder {

    // required uint32 key = 1;
    /**
     * <code>required uint32 key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required uint32 key = 1;</code>
     */
    int getKey();

    // optional uint32 valueId = 2 [default = 0];
    /**
     * <code>optional uint32 valueId = 2 [default = 0];</code>
     */
    boolean hasValueId();
    /**
     * <code>optional uint32 valueId = 2 [default = 0];</code>
     */
    int getValueId();

    // optional string value = 3;
    /**
     * <code>optional string value = 3;</code>
     */
    boolean hasValue();
    /**
     * <code>optional string value = 3;</code>
     */
    String getValue();
    /**
     * <code>optional string value = 3;</code>
     */
    com.google.protobuf.ByteString
    getValueBytes();
  }
  /**
   * Protobuf type {@code KeyValue}
   */
  public static final class KeyValue extends
          com.google.protobuf.GeneratedMessage
          implements KeyValueOrBuilder {
    // Use KeyValue.newBuilder() to construct.
    private KeyValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KeyValue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KeyValue defaultInstance;
    public static KeyValue getDefaultInstance() {
      return defaultInstance;
    }

    public KeyValue getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KeyValue(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                      extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              key_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              valueId_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              value_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return treeSem.proto.ProtoKeyValue.internal_static_KeyValue_descriptor;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return treeSem.proto.ProtoKeyValue.internal_static_KeyValue_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      treeSem.proto.ProtoKeyValue.KeyValue.class, treeSem.proto.ProtoKeyValue.KeyValue.Builder.class);
    }

    public static com.google.protobuf.Parser<KeyValue> PARSER =
            new com.google.protobuf.AbstractParser<KeyValue>() {
              public KeyValue parsePartialFrom(
                      com.google.protobuf.CodedInputStream input,
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                      throws com.google.protobuf.InvalidProtocolBufferException {
                return new KeyValue(input, extensionRegistry);
              }
            };

    @Override
    public com.google.protobuf.Parser<KeyValue> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required uint32 key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private int key_;
    /**
     * <code>required uint32 key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 key = 1;</code>
     */
    public int getKey() {
      return key_;
    }

    // optional uint32 valueId = 2 [default = 0];
    public static final int VALUEID_FIELD_NUMBER = 2;
    private int valueId_;
    /**
     * <code>optional uint32 valueId = 2 [default = 0];</code>
     */
    public boolean hasValueId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 valueId = 2 [default = 0];</code>
     */
    public int getValueId() {
      return valueId_;
    }

    // optional string value = 3;
    public static final int VALUE_FIELD_NUMBER = 3;
    private Object value_;
    /**
     * <code>optional string value = 3;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string value = 3;</code>
     */
    public String getValue() {
      Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string value = 3;</code>
     */
    public com.google.protobuf.ByteString
    getValueBytes() {
      Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      key_ = 0;
      valueId_ = 0;
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, valueId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt32Size(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
                .computeUInt32Size(2, valueId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
                .computeBytesSize(3, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
            throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof treeSem.proto.ProtoKeyValue.KeyValue)) {
        return super.equals(obj);
      }
      treeSem.proto.ProtoKeyValue.KeyValue other = (treeSem.proto.ProtoKeyValue.KeyValue) obj;

      boolean result = true;
      result = result && (hasKey() == other.hasKey());
      if (hasKey()) {
        result = result && (getKey()
                == other.getKey());
      }
      result = result && (hasValueId() == other.hasValueId());
      if (hasValueId()) {
        result = result && (getValueId()
                == other.getValueId());
      }
      result = result && (hasValue() == other.hasValue());
      if (hasValue()) {
        result = result && getValue()
                .equals(other.getValue());
      }
      result = result &&
              getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey();
      }
      if (hasValueId()) {
        hash = (37 * hash) + VALUEID_FIELD_NUMBER;
        hash = (53 * hash) + getValueId();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static treeSem.proto.ProtoKeyValue.KeyValue parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static treeSem.proto.ProtoKeyValue.KeyValue parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static treeSem.proto.ProtoKeyValue.KeyValue parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static treeSem.proto.ProtoKeyValue.KeyValue parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static treeSem.proto.ProtoKeyValue.KeyValue parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static treeSem.proto.ProtoKeyValue.KeyValue parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static treeSem.proto.ProtoKeyValue.KeyValue parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static treeSem.proto.ProtoKeyValue.KeyValue parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static treeSem.proto.ProtoKeyValue.KeyValue parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static treeSem.proto.ProtoKeyValue.KeyValue parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(treeSem.proto.ProtoKeyValue.KeyValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KeyValue}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder>
            implements treeSem.proto.ProtoKeyValue.KeyValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return treeSem.proto.ProtoKeyValue.internal_static_KeyValue_descriptor;
      }

      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return treeSem.proto.ProtoKeyValue.internal_static_KeyValue_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        treeSem.proto.ProtoKeyValue.KeyValue.class, treeSem.proto.ProtoKeyValue.KeyValue.Builder.class);
      }

      // Construct using treeSem.proto.ProtoKeyValue.KeyValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        valueId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return treeSem.proto.ProtoKeyValue.internal_static_KeyValue_descriptor;
      }

      public treeSem.proto.ProtoKeyValue.KeyValue getDefaultInstanceForType() {
        return treeSem.proto.ProtoKeyValue.KeyValue.getDefaultInstance();
      }

      public treeSem.proto.ProtoKeyValue.KeyValue build() {
        treeSem.proto.ProtoKeyValue.KeyValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public treeSem.proto.ProtoKeyValue.KeyValue buildPartial() {
        treeSem.proto.ProtoKeyValue.KeyValue result = new treeSem.proto.ProtoKeyValue.KeyValue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.valueId_ = valueId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof treeSem.proto.ProtoKeyValue.KeyValue) {
          return mergeFrom((treeSem.proto.ProtoKeyValue.KeyValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(treeSem.proto.ProtoKeyValue.KeyValue other) {
        if (other == treeSem.proto.ProtoKeyValue.KeyValue.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValueId()) {
          setValueId(other.getValueId());
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000004;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        treeSem.proto.ProtoKeyValue.KeyValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (treeSem.proto.ProtoKeyValue.KeyValue) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 key = 1;
      private int key_ ;
      /**
       * <code>required uint32 key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 key = 1;</code>
       */
      public int getKey() {
        return key_;
      }
      /**
       * <code>required uint32 key = 1;</code>
       */
      public Builder setKey(int value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 valueId = 2 [default = 0];
      private int valueId_ ;
      /**
       * <code>optional uint32 valueId = 2 [default = 0];</code>
       */
      public boolean hasValueId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 valueId = 2 [default = 0];</code>
       */
      public int getValueId() {
        return valueId_;
      }
      /**
       * <code>optional uint32 valueId = 2 [default = 0];</code>
       */
      public Builder setValueId(int value) {
        bitField0_ |= 0x00000002;
        valueId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 valueId = 2 [default = 0];</code>
       */
      public Builder clearValueId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        valueId_ = 0;
        onChanged();
        return this;
      }

      // optional string value = 3;
      private Object value_ = "";
      /**
       * <code>optional string value = 3;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string value = 3;</code>
       */
      public String getValue() {
        Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
                  .toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string value = 3;</code>
       */
      public com.google.protobuf.ByteString
      getValueBytes() {
        Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value = 3;</code>
       */
      public Builder setValue(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 3;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 3;</code>
       */
      public Builder setValueBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:KeyValue)
    }

    static {
      defaultInstance = new KeyValue(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:KeyValue)
  }

  public interface KeyValueListOrBuilder
          extends com.google.protobuf.MessageOrBuilder {

    // repeated .KeyValue list = 1;
    /**
     * <code>repeated .KeyValue list = 1;</code>
     */
    java.util.List<treeSem.proto.ProtoKeyValue.KeyValue>
    getListList();
    /**
     * <code>repeated .KeyValue list = 1;</code>
     */
    treeSem.proto.ProtoKeyValue.KeyValue getList(int index);
    /**
     * <code>repeated .KeyValue list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .KeyValue list = 1;</code>
     */
    java.util.List<? extends treeSem.proto.ProtoKeyValue.KeyValueOrBuilder>
    getListOrBuilderList();
    /**
     * <code>repeated .KeyValue list = 1;</code>
     */
    treeSem.proto.ProtoKeyValue.KeyValueOrBuilder getListOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code KeyValueList}
   */
  public static final class KeyValueList extends
          com.google.protobuf.GeneratedMessage
          implements KeyValueListOrBuilder {
    // Use KeyValueList.newBuilder() to construct.
    private KeyValueList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KeyValueList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KeyValueList defaultInstance;
    public static KeyValueList getDefaultInstance() {
      return defaultInstance;
    }

    public KeyValueList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KeyValueList(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                      extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                list_ = new java.util.ArrayList<treeSem.proto.ProtoKeyValue.KeyValue>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(input.readMessage(treeSem.proto.ProtoKeyValue.KeyValue.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return treeSem.proto.ProtoKeyValue.internal_static_KeyValueList_descriptor;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return treeSem.proto.ProtoKeyValue.internal_static_KeyValueList_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      treeSem.proto.ProtoKeyValue.KeyValueList.class, treeSem.proto.ProtoKeyValue.KeyValueList.Builder.class);
    }

    public static com.google.protobuf.Parser<KeyValueList> PARSER =
            new com.google.protobuf.AbstractParser<KeyValueList>() {
              public KeyValueList parsePartialFrom(
                      com.google.protobuf.CodedInputStream input,
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                      throws com.google.protobuf.InvalidProtocolBufferException {
                return new KeyValueList(input, extensionRegistry);
              }
            };

    @Override
    public com.google.protobuf.Parser<KeyValueList> getParserForType() {
      return PARSER;
    }

    // repeated .KeyValue list = 1;
    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<treeSem.proto.ProtoKeyValue.KeyValue> list_;
    /**
     * <code>repeated .KeyValue list = 1;</code>
     */
    public java.util.List<treeSem.proto.ProtoKeyValue.KeyValue> getListList() {
      return list_;
    }
    /**
     * <code>repeated .KeyValue list = 1;</code>
     */
    public java.util.List<? extends treeSem.proto.ProtoKeyValue.KeyValueOrBuilder>
    getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .KeyValue list = 1;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .KeyValue list = 1;</code>
     */
    public treeSem.proto.ProtoKeyValue.KeyValue getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .KeyValue list = 1;</code>
     */
    public treeSem.proto.ProtoKeyValue.KeyValueOrBuilder getListOrBuilder(
            int index) {
      return list_.get(index);
    }

    private void initFields() {
      list_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getListCount(); i++) {
        if (!getList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(1, list_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
            throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof treeSem.proto.ProtoKeyValue.KeyValueList)) {
        return super.equals(obj);
      }
      treeSem.proto.ProtoKeyValue.KeyValueList other = (treeSem.proto.ProtoKeyValue.KeyValueList) obj;

      boolean result = true;
      result = result && getListList()
              .equals(other.getListList());
      result = result &&
              getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static treeSem.proto.ProtoKeyValue.KeyValueList parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static treeSem.proto.ProtoKeyValue.KeyValueList parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static treeSem.proto.ProtoKeyValue.KeyValueList parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static treeSem.proto.ProtoKeyValue.KeyValueList parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static treeSem.proto.ProtoKeyValue.KeyValueList parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static treeSem.proto.ProtoKeyValue.KeyValueList parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static treeSem.proto.ProtoKeyValue.KeyValueList parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static treeSem.proto.ProtoKeyValue.KeyValueList parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static treeSem.proto.ProtoKeyValue.KeyValueList parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static treeSem.proto.ProtoKeyValue.KeyValueList parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(treeSem.proto.ProtoKeyValue.KeyValueList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KeyValueList}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder>
            implements treeSem.proto.ProtoKeyValue.KeyValueListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return treeSem.proto.ProtoKeyValue.internal_static_KeyValueList_descriptor;
      }

      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return treeSem.proto.ProtoKeyValue.internal_static_KeyValueList_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        treeSem.proto.ProtoKeyValue.KeyValueList.class, treeSem.proto.ProtoKeyValue.KeyValueList.Builder.class);
      }

      // Construct using treeSem.proto.ProtoKeyValue.KeyValueList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return treeSem.proto.ProtoKeyValue.internal_static_KeyValueList_descriptor;
      }

      public treeSem.proto.ProtoKeyValue.KeyValueList getDefaultInstanceForType() {
        return treeSem.proto.ProtoKeyValue.KeyValueList.getDefaultInstance();
      }

      public treeSem.proto.ProtoKeyValue.KeyValueList build() {
        treeSem.proto.ProtoKeyValue.KeyValueList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public treeSem.proto.ProtoKeyValue.KeyValueList buildPartial() {
        treeSem.proto.ProtoKeyValue.KeyValueList result = new treeSem.proto.ProtoKeyValue.KeyValueList(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof treeSem.proto.ProtoKeyValue.KeyValueList) {
          return mergeFrom((treeSem.proto.ProtoKeyValue.KeyValueList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(treeSem.proto.ProtoKeyValue.KeyValueList other) {
        if (other == treeSem.proto.ProtoKeyValue.KeyValueList.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ =
                      com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                              getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getListCount(); i++) {
          if (!getList(i).isInitialized()) {

            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        treeSem.proto.ProtoKeyValue.KeyValueList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (treeSem.proto.ProtoKeyValue.KeyValueList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .KeyValue list = 1;
      private java.util.List<treeSem.proto.ProtoKeyValue.KeyValue> list_ =
              java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = new java.util.ArrayList<treeSem.proto.ProtoKeyValue.KeyValue>(list_);
          bitField0_ |= 0x00000001;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
              treeSem.proto.ProtoKeyValue.KeyValue, treeSem.proto.ProtoKeyValue.KeyValue.Builder, treeSem.proto.ProtoKeyValue.KeyValueOrBuilder> listBuilder_;

      /**
       * <code>repeated .KeyValue list = 1;</code>
       */
      public java.util.List<treeSem.proto.ProtoKeyValue.KeyValue> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .KeyValue list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .KeyValue list = 1;</code>
       */
      public treeSem.proto.ProtoKeyValue.KeyValue getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .KeyValue list = 1;</code>
       */
      public Builder setList(
              int index, treeSem.proto.ProtoKeyValue.KeyValue value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValue list = 1;</code>
       */
      public Builder setList(
              int index, treeSem.proto.ProtoKeyValue.KeyValue.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KeyValue list = 1;</code>
       */
      public Builder addList(treeSem.proto.ProtoKeyValue.KeyValue value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValue list = 1;</code>
       */
      public Builder addList(
              int index, treeSem.proto.ProtoKeyValue.KeyValue value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValue list = 1;</code>
       */
      public Builder addList(
              treeSem.proto.ProtoKeyValue.KeyValue.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KeyValue list = 1;</code>
       */
      public Builder addList(
              int index, treeSem.proto.ProtoKeyValue.KeyValue.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KeyValue list = 1;</code>
       */
      public Builder addAllList(
              Iterable<? extends treeSem.proto.ProtoKeyValue.KeyValue> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          super.addAll(values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValue list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .KeyValue list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValue list = 1;</code>
       */
      public treeSem.proto.ProtoKeyValue.KeyValue.Builder getListBuilder(
              int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .KeyValue list = 1;</code>
       */
      public treeSem.proto.ProtoKeyValue.KeyValueOrBuilder getListOrBuilder(
              int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .KeyValue list = 1;</code>
       */
      public java.util.List<? extends treeSem.proto.ProtoKeyValue.KeyValueOrBuilder>
      getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .KeyValue list = 1;</code>
       */
      public treeSem.proto.ProtoKeyValue.KeyValue.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
                treeSem.proto.ProtoKeyValue.KeyValue.getDefaultInstance());
      }
      /**
       * <code>repeated .KeyValue list = 1;</code>
       */
      public treeSem.proto.ProtoKeyValue.KeyValue.Builder addListBuilder(
              int index) {
        return getListFieldBuilder().addBuilder(
                index, treeSem.proto.ProtoKeyValue.KeyValue.getDefaultInstance());
      }
      /**
       * <code>repeated .KeyValue list = 1;</code>
       */
      public java.util.List<treeSem.proto.ProtoKeyValue.KeyValue.Builder>
      getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
              treeSem.proto.ProtoKeyValue.KeyValue, treeSem.proto.ProtoKeyValue.KeyValue.Builder, treeSem.proto.ProtoKeyValue.KeyValueOrBuilder>
      getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                  treeSem.proto.ProtoKeyValue.KeyValue, treeSem.proto.ProtoKeyValue.KeyValue.Builder, treeSem.proto.ProtoKeyValue.KeyValueOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:KeyValueList)
    }

    static {
      defaultInstance = new KeyValueList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:KeyValueList)
  }

  public interface OListOrBuilder
          extends com.google.protobuf.MessageOrBuilder {

    // repeated .KeyValueList attu = 1;
    /**
     * <code>repeated .KeyValueList attu = 1;</code>
     */
    java.util.List<treeSem.proto.ProtoKeyValue.KeyValueList>
    getAttuList();
    /**
     * <code>repeated .KeyValueList attu = 1;</code>
     */
    treeSem.proto.ProtoKeyValue.KeyValueList getAttu(int index);
    /**
     * <code>repeated .KeyValueList attu = 1;</code>
     */
    int getAttuCount();
    /**
     * <code>repeated .KeyValueList attu = 1;</code>
     */
    java.util.List<? extends treeSem.proto.ProtoKeyValue.KeyValueListOrBuilder>
    getAttuOrBuilderList();
    /**
     * <code>repeated .KeyValueList attu = 1;</code>
     */
    treeSem.proto.ProtoKeyValue.KeyValueListOrBuilder getAttuOrBuilder(
            int index);

    // repeated .KeyValueList tag = 2;
    /**
     * <code>repeated .KeyValueList tag = 2;</code>
     */
    java.util.List<treeSem.proto.ProtoKeyValue.KeyValueList>
    getTagList();
    /**
     * <code>repeated .KeyValueList tag = 2;</code>
     */
    treeSem.proto.ProtoKeyValue.KeyValueList getTag(int index);
    /**
     * <code>repeated .KeyValueList tag = 2;</code>
     */
    int getTagCount();
    /**
     * <code>repeated .KeyValueList tag = 2;</code>
     */
    java.util.List<? extends treeSem.proto.ProtoKeyValue.KeyValueListOrBuilder>
    getTagOrBuilderList();
    /**
     * <code>repeated .KeyValueList tag = 2;</code>
     */
    treeSem.proto.ProtoKeyValue.KeyValueListOrBuilder getTagOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code OList}
   */
  public static final class OList extends
          com.google.protobuf.GeneratedMessage
          implements OListOrBuilder {
    // Use OList.newBuilder() to construct.
    private OList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OList defaultInstance;
    public static OList getDefaultInstance() {
      return defaultInstance;
    }

    public OList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OList(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                      extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                attu_ = new java.util.ArrayList<treeSem.proto.ProtoKeyValue.KeyValueList>();
                mutable_bitField0_ |= 0x00000001;
              }
              attu_.add(input.readMessage(treeSem.proto.ProtoKeyValue.KeyValueList.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                tag_ = new java.util.ArrayList<treeSem.proto.ProtoKeyValue.KeyValueList>();
                mutable_bitField0_ |= 0x00000002;
              }
              tag_.add(input.readMessage(treeSem.proto.ProtoKeyValue.KeyValueList.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          attu_ = java.util.Collections.unmodifiableList(attu_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          tag_ = java.util.Collections.unmodifiableList(tag_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return treeSem.proto.ProtoKeyValue.internal_static_OList_descriptor;
    }

    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return treeSem.proto.ProtoKeyValue.internal_static_OList_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      treeSem.proto.ProtoKeyValue.OList.class, treeSem.proto.ProtoKeyValue.OList.Builder.class);
    }

    public static com.google.protobuf.Parser<OList> PARSER =
            new com.google.protobuf.AbstractParser<OList>() {
              public OList parsePartialFrom(
                      com.google.protobuf.CodedInputStream input,
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                      throws com.google.protobuf.InvalidProtocolBufferException {
                return new OList(input, extensionRegistry);
              }
            };

    @Override
    public com.google.protobuf.Parser<OList> getParserForType() {
      return PARSER;
    }

    // repeated .KeyValueList attu = 1;
    public static final int ATTU_FIELD_NUMBER = 1;
    private java.util.List<treeSem.proto.ProtoKeyValue.KeyValueList> attu_;
    /**
     * <code>repeated .KeyValueList attu = 1;</code>
     */
    public java.util.List<treeSem.proto.ProtoKeyValue.KeyValueList> getAttuList() {
      return attu_;
    }
    /**
     * <code>repeated .KeyValueList attu = 1;</code>
     */
    public java.util.List<? extends treeSem.proto.ProtoKeyValue.KeyValueListOrBuilder>
    getAttuOrBuilderList() {
      return attu_;
    }
    /**
     * <code>repeated .KeyValueList attu = 1;</code>
     */
    public int getAttuCount() {
      return attu_.size();
    }
    /**
     * <code>repeated .KeyValueList attu = 1;</code>
     */
    public treeSem.proto.ProtoKeyValue.KeyValueList getAttu(int index) {
      return attu_.get(index);
    }
    /**
     * <code>repeated .KeyValueList attu = 1;</code>
     */
    public treeSem.proto.ProtoKeyValue.KeyValueListOrBuilder getAttuOrBuilder(
            int index) {
      return attu_.get(index);
    }

    // repeated .KeyValueList tag = 2;
    public static final int TAG_FIELD_NUMBER = 2;
    private java.util.List<treeSem.proto.ProtoKeyValue.KeyValueList> tag_;
    /**
     * <code>repeated .KeyValueList tag = 2;</code>
     */
    public java.util.List<treeSem.proto.ProtoKeyValue.KeyValueList> getTagList() {
      return tag_;
    }
    /**
     * <code>repeated .KeyValueList tag = 2;</code>
     */
    public java.util.List<? extends treeSem.proto.ProtoKeyValue.KeyValueListOrBuilder>
    getTagOrBuilderList() {
      return tag_;
    }
    /**
     * <code>repeated .KeyValueList tag = 2;</code>
     */
    public int getTagCount() {
      return tag_.size();
    }
    /**
     * <code>repeated .KeyValueList tag = 2;</code>
     */
    public treeSem.proto.ProtoKeyValue.KeyValueList getTag(int index) {
      return tag_.get(index);
    }
    /**
     * <code>repeated .KeyValueList tag = 2;</code>
     */
    public treeSem.proto.ProtoKeyValue.KeyValueListOrBuilder getTagOrBuilder(
            int index) {
      return tag_.get(index);
    }

    private void initFields() {
      attu_ = java.util.Collections.emptyList();
      tag_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getAttuCount(); i++) {
        if (!getAttu(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getTagCount(); i++) {
        if (!getTag(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < attu_.size(); i++) {
        output.writeMessage(1, attu_.get(i));
      }
      for (int i = 0; i < tag_.size(); i++) {
        output.writeMessage(2, tag_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < attu_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(1, attu_.get(i));
      }
      for (int i = 0; i < tag_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(2, tag_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
            throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof treeSem.proto.ProtoKeyValue.OList)) {
        return super.equals(obj);
      }
      treeSem.proto.ProtoKeyValue.OList other = (treeSem.proto.ProtoKeyValue.OList) obj;

      boolean result = true;
      result = result && getAttuList()
              .equals(other.getAttuList());
      result = result && getTagList()
              .equals(other.getTagList());
      result = result &&
              getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getAttuCount() > 0) {
        hash = (37 * hash) + ATTU_FIELD_NUMBER;
        hash = (53 * hash) + getAttuList().hashCode();
      }
      if (getTagCount() > 0) {
        hash = (37 * hash) + TAG_FIELD_NUMBER;
        hash = (53 * hash) + getTagList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static treeSem.proto.ProtoKeyValue.OList parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static treeSem.proto.ProtoKeyValue.OList parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static treeSem.proto.ProtoKeyValue.OList parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static treeSem.proto.ProtoKeyValue.OList parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static treeSem.proto.ProtoKeyValue.OList parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static treeSem.proto.ProtoKeyValue.OList parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static treeSem.proto.ProtoKeyValue.OList parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static treeSem.proto.ProtoKeyValue.OList parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static treeSem.proto.ProtoKeyValue.OList parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static treeSem.proto.ProtoKeyValue.OList parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(treeSem.proto.ProtoKeyValue.OList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OList}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder>
            implements treeSem.proto.ProtoKeyValue.OListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return treeSem.proto.ProtoKeyValue.internal_static_OList_descriptor;
      }

      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return treeSem.proto.ProtoKeyValue.internal_static_OList_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        treeSem.proto.ProtoKeyValue.OList.class, treeSem.proto.ProtoKeyValue.OList.Builder.class);
      }

      // Construct using treeSem.proto.ProtoKeyValue.OList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAttuFieldBuilder();
          getTagFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (attuBuilder_ == null) {
          attu_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          attuBuilder_.clear();
        }
        if (tagBuilder_ == null) {
          tag_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          tagBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return treeSem.proto.ProtoKeyValue.internal_static_OList_descriptor;
      }

      public treeSem.proto.ProtoKeyValue.OList getDefaultInstanceForType() {
        return treeSem.proto.ProtoKeyValue.OList.getDefaultInstance();
      }

      public treeSem.proto.ProtoKeyValue.OList build() {
        treeSem.proto.ProtoKeyValue.OList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public treeSem.proto.ProtoKeyValue.OList buildPartial() {
        treeSem.proto.ProtoKeyValue.OList result = new treeSem.proto.ProtoKeyValue.OList(this);
        int from_bitField0_ = bitField0_;
        if (attuBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            attu_ = java.util.Collections.unmodifiableList(attu_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.attu_ = attu_;
        } else {
          result.attu_ = attuBuilder_.build();
        }
        if (tagBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            tag_ = java.util.Collections.unmodifiableList(tag_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.tag_ = tag_;
        } else {
          result.tag_ = tagBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof treeSem.proto.ProtoKeyValue.OList) {
          return mergeFrom((treeSem.proto.ProtoKeyValue.OList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(treeSem.proto.ProtoKeyValue.OList other) {
        if (other == treeSem.proto.ProtoKeyValue.OList.getDefaultInstance()) return this;
        if (attuBuilder_ == null) {
          if (!other.attu_.isEmpty()) {
            if (attu_.isEmpty()) {
              attu_ = other.attu_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAttuIsMutable();
              attu_.addAll(other.attu_);
            }
            onChanged();
          }
        } else {
          if (!other.attu_.isEmpty()) {
            if (attuBuilder_.isEmpty()) {
              attuBuilder_.dispose();
              attuBuilder_ = null;
              attu_ = other.attu_;
              bitField0_ = (bitField0_ & ~0x00000001);
              attuBuilder_ =
                      com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                              getAttuFieldBuilder() : null;
            } else {
              attuBuilder_.addAllMessages(other.attu_);
            }
          }
        }
        if (tagBuilder_ == null) {
          if (!other.tag_.isEmpty()) {
            if (tag_.isEmpty()) {
              tag_ = other.tag_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTagIsMutable();
              tag_.addAll(other.tag_);
            }
            onChanged();
          }
        } else {
          if (!other.tag_.isEmpty()) {
            if (tagBuilder_.isEmpty()) {
              tagBuilder_.dispose();
              tagBuilder_ = null;
              tag_ = other.tag_;
              bitField0_ = (bitField0_ & ~0x00000002);
              tagBuilder_ =
                      com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                              getTagFieldBuilder() : null;
            } else {
              tagBuilder_.addAllMessages(other.tag_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getAttuCount(); i++) {
          if (!getAttu(i).isInitialized()) {

            return false;
          }
        }
        for (int i = 0; i < getTagCount(); i++) {
          if (!getTag(i).isInitialized()) {

            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        treeSem.proto.ProtoKeyValue.OList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (treeSem.proto.ProtoKeyValue.OList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .KeyValueList attu = 1;
      private java.util.List<treeSem.proto.ProtoKeyValue.KeyValueList> attu_ =
              java.util.Collections.emptyList();
      private void ensureAttuIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          attu_ = new java.util.ArrayList<treeSem.proto.ProtoKeyValue.KeyValueList>(attu_);
          bitField0_ |= 0x00000001;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
              treeSem.proto.ProtoKeyValue.KeyValueList, treeSem.proto.ProtoKeyValue.KeyValueList.Builder, treeSem.proto.ProtoKeyValue.KeyValueListOrBuilder> attuBuilder_;

      /**
       * <code>repeated .KeyValueList attu = 1;</code>
       */
      public java.util.List<treeSem.proto.ProtoKeyValue.KeyValueList> getAttuList() {
        if (attuBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attu_);
        } else {
          return attuBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .KeyValueList attu = 1;</code>
       */
      public int getAttuCount() {
        if (attuBuilder_ == null) {
          return attu_.size();
        } else {
          return attuBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .KeyValueList attu = 1;</code>
       */
      public treeSem.proto.ProtoKeyValue.KeyValueList getAttu(int index) {
        if (attuBuilder_ == null) {
          return attu_.get(index);
        } else {
          return attuBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .KeyValueList attu = 1;</code>
       */
      public Builder setAttu(
              int index, treeSem.proto.ProtoKeyValue.KeyValueList value) {
        if (attuBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttuIsMutable();
          attu_.set(index, value);
          onChanged();
        } else {
          attuBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueList attu = 1;</code>
       */
      public Builder setAttu(
              int index, treeSem.proto.ProtoKeyValue.KeyValueList.Builder builderForValue) {
        if (attuBuilder_ == null) {
          ensureAttuIsMutable();
          attu_.set(index, builderForValue.build());
          onChanged();
        } else {
          attuBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueList attu = 1;</code>
       */
      public Builder addAttu(treeSem.proto.ProtoKeyValue.KeyValueList value) {
        if (attuBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttuIsMutable();
          attu_.add(value);
          onChanged();
        } else {
          attuBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueList attu = 1;</code>
       */
      public Builder addAttu(
              int index, treeSem.proto.ProtoKeyValue.KeyValueList value) {
        if (attuBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttuIsMutable();
          attu_.add(index, value);
          onChanged();
        } else {
          attuBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueList attu = 1;</code>
       */
      public Builder addAttu(
              treeSem.proto.ProtoKeyValue.KeyValueList.Builder builderForValue) {
        if (attuBuilder_ == null) {
          ensureAttuIsMutable();
          attu_.add(builderForValue.build());
          onChanged();
        } else {
          attuBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueList attu = 1;</code>
       */
      public Builder addAttu(
              int index, treeSem.proto.ProtoKeyValue.KeyValueList.Builder builderForValue) {
        if (attuBuilder_ == null) {
          ensureAttuIsMutable();
          attu_.add(index, builderForValue.build());
          onChanged();
        } else {
          attuBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueList attu = 1;</code>
       */
      public Builder addAllAttu(
              Iterable<? extends treeSem.proto.ProtoKeyValue.KeyValueList> values) {
        if (attuBuilder_ == null) {
          ensureAttuIsMutable();
          super.addAll(values, attu_);
          onChanged();
        } else {
          attuBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueList attu = 1;</code>
       */
      public Builder clearAttu() {
        if (attuBuilder_ == null) {
          attu_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          attuBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueList attu = 1;</code>
       */
      public Builder removeAttu(int index) {
        if (attuBuilder_ == null) {
          ensureAttuIsMutable();
          attu_.remove(index);
          onChanged();
        } else {
          attuBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueList attu = 1;</code>
       */
      public treeSem.proto.ProtoKeyValue.KeyValueList.Builder getAttuBuilder(
              int index) {
        return getAttuFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .KeyValueList attu = 1;</code>
       */
      public treeSem.proto.ProtoKeyValue.KeyValueListOrBuilder getAttuOrBuilder(
              int index) {
        if (attuBuilder_ == null) {
          return attu_.get(index);  } else {
          return attuBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .KeyValueList attu = 1;</code>
       */
      public java.util.List<? extends treeSem.proto.ProtoKeyValue.KeyValueListOrBuilder>
      getAttuOrBuilderList() {
        if (attuBuilder_ != null) {
          return attuBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attu_);
        }
      }
      /**
       * <code>repeated .KeyValueList attu = 1;</code>
       */
      public treeSem.proto.ProtoKeyValue.KeyValueList.Builder addAttuBuilder() {
        return getAttuFieldBuilder().addBuilder(
                treeSem.proto.ProtoKeyValue.KeyValueList.getDefaultInstance());
      }
      /**
       * <code>repeated .KeyValueList attu = 1;</code>
       */
      public treeSem.proto.ProtoKeyValue.KeyValueList.Builder addAttuBuilder(
              int index) {
        return getAttuFieldBuilder().addBuilder(
                index, treeSem.proto.ProtoKeyValue.KeyValueList.getDefaultInstance());
      }
      /**
       * <code>repeated .KeyValueList attu = 1;</code>
       */
      public java.util.List<treeSem.proto.ProtoKeyValue.KeyValueList.Builder>
      getAttuBuilderList() {
        return getAttuFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
              treeSem.proto.ProtoKeyValue.KeyValueList, treeSem.proto.ProtoKeyValue.KeyValueList.Builder, treeSem.proto.ProtoKeyValue.KeyValueListOrBuilder>
      getAttuFieldBuilder() {
        if (attuBuilder_ == null) {
          attuBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                  treeSem.proto.ProtoKeyValue.KeyValueList, treeSem.proto.ProtoKeyValue.KeyValueList.Builder, treeSem.proto.ProtoKeyValue.KeyValueListOrBuilder>(
                  attu_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          attu_ = null;
        }
        return attuBuilder_;
      }

      // repeated .KeyValueList tag = 2;
      private java.util.List<treeSem.proto.ProtoKeyValue.KeyValueList> tag_ =
              java.util.Collections.emptyList();
      private void ensureTagIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          tag_ = new java.util.ArrayList<treeSem.proto.ProtoKeyValue.KeyValueList>(tag_);
          bitField0_ |= 0x00000002;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
              treeSem.proto.ProtoKeyValue.KeyValueList, treeSem.proto.ProtoKeyValue.KeyValueList.Builder, treeSem.proto.ProtoKeyValue.KeyValueListOrBuilder> tagBuilder_;

      /**
       * <code>repeated .KeyValueList tag = 2;</code>
       */
      public java.util.List<treeSem.proto.ProtoKeyValue.KeyValueList> getTagList() {
        if (tagBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tag_);
        } else {
          return tagBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .KeyValueList tag = 2;</code>
       */
      public int getTagCount() {
        if (tagBuilder_ == null) {
          return tag_.size();
        } else {
          return tagBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .KeyValueList tag = 2;</code>
       */
      public treeSem.proto.ProtoKeyValue.KeyValueList getTag(int index) {
        if (tagBuilder_ == null) {
          return tag_.get(index);
        } else {
          return tagBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .KeyValueList tag = 2;</code>
       */
      public Builder setTag(
              int index, treeSem.proto.ProtoKeyValue.KeyValueList value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.set(index, value);
          onChanged();
        } else {
          tagBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueList tag = 2;</code>
       */
      public Builder setTag(
              int index, treeSem.proto.ProtoKeyValue.KeyValueList.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.set(index, builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueList tag = 2;</code>
       */
      public Builder addTag(treeSem.proto.ProtoKeyValue.KeyValueList value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.add(value);
          onChanged();
        } else {
          tagBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueList tag = 2;</code>
       */
      public Builder addTag(
              int index, treeSem.proto.ProtoKeyValue.KeyValueList value) {
        if (tagBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagIsMutable();
          tag_.add(index, value);
          onChanged();
        } else {
          tagBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueList tag = 2;</code>
       */
      public Builder addTag(
              treeSem.proto.ProtoKeyValue.KeyValueList.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.add(builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueList tag = 2;</code>
       */
      public Builder addTag(
              int index, treeSem.proto.ProtoKeyValue.KeyValueList.Builder builderForValue) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.add(index, builderForValue.build());
          onChanged();
        } else {
          tagBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueList tag = 2;</code>
       */
      public Builder addAllTag(
              Iterable<? extends treeSem.proto.ProtoKeyValue.KeyValueList> values) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          super.addAll(values, tag_);
          onChanged();
        } else {
          tagBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueList tag = 2;</code>
       */
      public Builder clearTag() {
        if (tagBuilder_ == null) {
          tag_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          tagBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueList tag = 2;</code>
       */
      public Builder removeTag(int index) {
        if (tagBuilder_ == null) {
          ensureTagIsMutable();
          tag_.remove(index);
          onChanged();
        } else {
          tagBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .KeyValueList tag = 2;</code>
       */
      public treeSem.proto.ProtoKeyValue.KeyValueList.Builder getTagBuilder(
              int index) {
        return getTagFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .KeyValueList tag = 2;</code>
       */
      public treeSem.proto.ProtoKeyValue.KeyValueListOrBuilder getTagOrBuilder(
              int index) {
        if (tagBuilder_ == null) {
          return tag_.get(index);  } else {
          return tagBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .KeyValueList tag = 2;</code>
       */
      public java.util.List<? extends treeSem.proto.ProtoKeyValue.KeyValueListOrBuilder>
      getTagOrBuilderList() {
        if (tagBuilder_ != null) {
          return tagBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tag_);
        }
      }
      /**
       * <code>repeated .KeyValueList tag = 2;</code>
       */
      public treeSem.proto.ProtoKeyValue.KeyValueList.Builder addTagBuilder() {
        return getTagFieldBuilder().addBuilder(
                treeSem.proto.ProtoKeyValue.KeyValueList.getDefaultInstance());
      }
      /**
       * <code>repeated .KeyValueList tag = 2;</code>
       */
      public treeSem.proto.ProtoKeyValue.KeyValueList.Builder addTagBuilder(
              int index) {
        return getTagFieldBuilder().addBuilder(
                index, treeSem.proto.ProtoKeyValue.KeyValueList.getDefaultInstance());
      }
      /**
       * <code>repeated .KeyValueList tag = 2;</code>
       */
      public java.util.List<treeSem.proto.ProtoKeyValue.KeyValueList.Builder>
      getTagBuilderList() {
        return getTagFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
              treeSem.proto.ProtoKeyValue.KeyValueList, treeSem.proto.ProtoKeyValue.KeyValueList.Builder, treeSem.proto.ProtoKeyValue.KeyValueListOrBuilder>
      getTagFieldBuilder() {
        if (tagBuilder_ == null) {
          tagBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                  treeSem.proto.ProtoKeyValue.KeyValueList, treeSem.proto.ProtoKeyValue.KeyValueList.Builder, treeSem.proto.ProtoKeyValue.KeyValueListOrBuilder>(
                  tag_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          tag_ = null;
        }
        return tagBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:OList)
    }

    static {
      defaultInstance = new OList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OList)
  }

  private static com.google.protobuf.Descriptors.Descriptor
          internal_static_KeyValue_descriptor;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_KeyValue_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
          internal_static_KeyValueList_descriptor;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_KeyValueList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
          internal_static_OList_descriptor;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_OList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    String[] descriptorData = {
            "\n\023ProtoKeyValue.proto\":\n\010KeyValue\022\013\n\003key" +
                    "\030\001 \002(\r\022\022\n\007valueId\030\002 \001(\r:\0010\022\r\n\005value\030\003 \001(" +
                    "\t\"\'\n\014KeyValueList\022\027\n\004list\030\001 \003(\0132\t.KeyVal" +
                    "ue\"@\n\005OList\022\033\n\004attu\030\001 \003(\0132\r.KeyValueList" +
                    "\022\032\n\003tag\030\002 \003(\0132\r.KeyValueListB-\n\027com.hype" +
                    "rs.gmi.db.protoB\rProtoKeyValueH\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_KeyValue_descriptor =
                        getDescriptor().getMessageTypes().get(0);
                internal_static_KeyValue_fieldAccessorTable = new
                        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_KeyValue_descriptor,
                        new String[] { "Key", "ValueId", "Value", });
                internal_static_KeyValueList_descriptor =
                        getDescriptor().getMessageTypes().get(1);
                internal_static_KeyValueList_fieldAccessorTable = new
                        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_KeyValueList_descriptor,
                        new String[] { "List", });
                internal_static_OList_descriptor =
                        getDescriptor().getMessageTypes().get(2);
                internal_static_OList_fieldAccessorTable = new
                        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_OList_descriptor,
                        new String[] { "Attu", "Tag", });
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
